
# 3. Stages for setting up the user and the development environment.
########################################################################

ARG GENERIC_IMAGE

########################################################################
# Final runtime layer for the user.
# Explicitly create a user for Docker Engine interfaces
# which do no support selecting the user at runtime; this is the case for Run:ai.

# FROM ${GENERIC_IMAGE}:latest-vllm-root AS runtime-user
# FROM ${GENERIC_IMAGE}:latest-vllm-miczhang as runtime-user
FROM registry.rcp.epfl.ch/multimeditron/basic:latest-vllm-sallinen as runtime-user

ARG GRPID
ARG USRID
ARG GRP
ARG USR
ARG PASSWD
ENV PASSWD=${PASSWD}

# Add user to sudoer to be able to install apt packages.
RUN sudo groupadd -f -g ${GRPID} ${GRP} && \
    sudo useradd --shell /bin/zsh --create-home -u ${USRID} -g ${GRP} -p  $(openssl passwd -1 ${PASSWD}) ${USR} && \
    sudo usermod -aG sudo ${USR}

USER ${USR}
RUN touch /home/${USR}/.zshrc
