########################################################################
# 3. Stages for setting up the user and the development environment.
########################################################################

ARG GENERIC_IMAGE

########################################################################
# Final runtime layer for the user.
# Explicitly create a user for Docker Engine interfaces
# which do no support selecting the user at runtime; this is the case for Run:ai.

FROM ${GENERIC_IMAGE}:latest-gboye AS training-image

# Add user to sudoer to be able to install apt packages.
COPY dependencies/requirements.txt .
RUN pip install -r requirements.txt

